apiVersion: v1
kind: ConfigMap
data:
  backend-server-slots-increment: "4"
  dynamic-scaling: "true"
metadata:
  name: syntasa-ingress-conf
  namespace: {{ .Values.namespace }}

---
{{- if .Values.reportingSecret }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ubbagent-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    identities:
    - name: gcp
      gcp:
        encodedServiceAccountKey: $AGENT_ENCODED_KEY

    metrics:
    - name: syntasa_byol_timebased_usage
      type: int

      endpoints:
      - name: on_disk
      - name: servicecontrol

      aggregation:
        bufferSeconds: 60

    - name: instance_time
      type: int
      endpoints:
      - name: on_disk
      - name: servicecontrol

      passthrough: {}

    endpoints:
    - name: on_disk
      disk:
        reportDir: /var/lib/ubbagent/reports
        expireSeconds: 3600
    - name: servicecontrol
      servicecontrol:
        identity: gcp
        serviceName: syntasa-behaviorial-sentiment-analytics.endpoints.syntasa-public.cloud.goog
        consumerId: $AGENT_CONSUMER_ID

    sources:
    - name: instance_time_heartbeat
      heartbeat:
        metric: syntasa_byol_timebased_usage
        intervalSeconds: 60
        value:
          int64Value: 60
{{- end }}