apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.haproxy.name }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.haproxy.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ .Values.haproxy.name }}
  template:
    metadata:
      labels:
        run: {{ .Values.haproxy.name }}
    spec:
      serviceAccountName: {{ .Values.roles.serviceAccount }}
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: {{ .Values.haproxy.name }}
          image: "{{ .Values.haproxyIngressImage }}"
          imagePullPolicy: "Always"
          args:
            - --configmap={{ .Values.namespace }}/syntasa-ingress-conf
            - --default-ssl-certificate={{ .Values.namespace }}/{{ .Values.cert.name }}
          ports:
            {{- range .Values.haproxy.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          env:
            - name: POD_NAME
              value: {{ .Values.haproxy.name }}
            - name: POD_NAMESPACE
              value: {{ .Values.namespace }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.haproxy.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.haproxy.name }}
spec:
  selector:
    run: {{ .Values.haproxy.name }}
  ports:
    - port: {{ .Values.haproxy.service.port }}
      targetPort: {{ .Values.haproxy.service.targetPort }}
  type: {{ .Values.haproxy.service.type }}
  {{- if .Values.haproxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.haproxy.service.loadBalancerIP }}
  {{- end }}
  loadBalancerSourceRanges:
    {{ range splitList "," .Values.haproxy.service.loadBalancerSourceRanges }}
    - {{.}}
  {{ end }}
