
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cert.name }}
  namespace: {{ .Values.namespace }}
data:
  tls.key: {{ .Values.TLS_CERTIFICATE_KEY }}
  tls.crt: {{ .Values.TLS_CERTIFICATE_CRT }}

---
apiVersion: v1
kind: Secret
metadata:
  name: syntasa-service-account-secret
  namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "dockerconfigjson" . | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.namespace }}-notebooks
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "dockerconfigjson" . | b64enc | quote }}
---