
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.cert.name }}
  namespace: {{ .Values.namespace }}
data:
  tls.key: {{ .Values.TLS_CERTIFICATE_KEY }}
  tls.crt: {{ .Values.TLS_CERTIFICATE_CRT }}

---
apiVersion: v1
kind: Secret
metadata:
  name: syntasa-service-account-secret
  namespace: {{ .Values.namespace }}
