apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebooks-sa
  namespace: {{ .Values.namespace }}-notebooks
  {{- if eq .Values.cloudProvider "gcp" }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount }}
  {{- end }}
imagePullSecrets:
- name: {{ .Values.imagePullSecrets.name }}
secrets:
- name: syntasa-notebook-service-account-secret
automountServiceAccountToken: true

---
apiVersion: v1
kind: Secret
metadata:
  name: syntasa-notebook-service-account-secret
  namespace: {{ .Values.namespace }}-notebooks
type: Opaque

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: syntasa-notebook-sa-role-binding
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "cluster-admin"
subjects:
- kind: "ServiceAccount"
  name: notebooks-sa
  namespace: {{ .Values.namespace }}-notebooks

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syntasa-service-account
  namespace: {{ .Values.namespace }}
  {{- if eq .Values.cloudProvider "gcp" }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount }}
  {{- end }}