
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.roles.serviceAccount }}
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount }}
secrets:
  - name: {{ .Values.imagePullSecrets.name }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecrets.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syntasa-service-account
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebooks-sa
  namespace: {{ .Values.namespace }}-notebooks
  annotations:
    "iam.gke.io/gcp-service-account": {{ .Values.gcpServiceAccount }}
imagePullSecrets:
- name: {{ .Values.imagePullSecrets.name }}
secrets:
- name: syntasa-notebook-service-account-secret
automountServiceAccountToken: true

---
apiVersion: v1
kind: Secret
metadata:
  name: syntasa-notebook-service-account-secret
  namespace: {{ .Values.namespace }}-notebooks
type: Opaque

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syntasa-sa-role
rules:
- apiGroups: ["", "networking.k8s.io", "rbac.authorization.k8s.io", "apps", "apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syntasa-sa-role-binding
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "syntasa-sa-role"
subjects:
- kind: "ServiceAccount"
  name: {{ .Values.roles.serviceAccount }}
  namespace: {{ .Values.namespace }}
- kind: "ServiceAccount"
  name: notebooks-sa
  namespace: {{ .Values.namespace }}-notebooks
---